repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args:
          - --branch=main
      - id: debug-statements
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.4'
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: []
        exclude_types: [csv, json]
        exclude: ^tests/fixtures/
        additional_dependencies:
          - tomli

  # - repo: local
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       entry: script/run-in-env.sh pylint -j 0
  #       language: script
  #       types: [python]
  #       files: ^music_assistant/.+\.py$

  #     - id: mypy
  #       name: mypy
  #       entry: script/run-in-env.sh mypy
  #       language: script
  #       types: [python]
  #       files: ^music_assistant/.+\.py$

  - repo: local
    hooks:
      - id: gen_requirements_all
        name: gen_requirements_all
        entry: script/run-in-env.sh python3 -m script.gen_requirements_all
        pass_filenames: false
        language: script
        types: [text]
        files: ^(music_assistant/.+/manifest\.json|pyproject\.toml|\.pre-commit-config\.yaml|script/gen_requirements_all\.py)$
